### PR TITLE
Feature/zk enseble string

### PR DESCRIPTION
**Pull request by piavlo**
PR for #18

### CODE REVIEW

**Comment by dim** [comment]
I am not sure it's really essential. I like the current API because it's expecting consistent inputs for brokers and zookeepers. Plus, it would be a breaking change and would require a major release

**Comment by knarewski** [comment]
+1
Please mind, that someone may need to add a scope to his zk connection (like in PR's example: `zk1:2181,zk2:2181,zk1:2181/kafka`).

If you want to avoid inconsistency, maybe it's a good idea to add possibility to make a suffix as an option? What do you think?

**Comment by dim** [comment]
@knarewski please see my response in https://github.com/bsm/poseidon_cluster/issues/18#issuecomment-131636417

**Comment by knarewski** [comment]
Right, I missed it, thanks

**Pull request closed without merging**
